title: "フロントエンドでclean architectureを実践する"
summary: "フロントエンドでclean architectureを実践するためのチュートリアル"
topics: ["react", "typescript", "clean architecture", "vitest"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 1_introduction
  - conclusion
